import "antd/dist/reset.css";

import BasicLayout from "./BasicLayout";
import Providers from "./Providers";

import "@/styles/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <BasicLayout>{children}</BasicLayout>
        </Providers>
      </body>
    </html>
  );
}
