name: 👀 Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    name: 🅿 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: true

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: 🔬 Format
        run: pnpm format:ci

  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: true

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: 🔬 Lint
        run: pnpm lint:ci

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: true

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: 🔎 Type check
        run: pnpm typecheck

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    env:
      TEST_TIMEOUT: 20000
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: true

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: ⚡ Run vitest
        run: pnpm test:ci

      - name: Publish Vitest Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: (!cancelled())
        with:
          check_name: Vitest Test Results
          files: |
            coverage/junit.xml

  playwright:
    name: 🎭 Playwright
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    timeout-minutes: 30
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: true

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: 📥 Install Playwright Browsers
        run: pnpm test:e2e:install

      - name: 🎭 Playwright tests
        run: pnpm test:e2e:ci

      - name: Publish Playwright Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: (!cancelled())
        with:
          check_name: Playwright Test Results
          files: |
            playwright-report/junit.xml

      - name: 📊 Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
